import { LightningElement } from 'lwc';

export default class About extends LightningElement {
    decade1 = false;
    decade2 = false;
    decade3 = false;


    decadechange1(){
        this.decade1 = !this.decade1;
    };
    decadechange2(){
        this.decade2 = !this.decade2;
    };
    decadechange3(){
        this.decade3 = !this.decade3;
    };
    

    decade1999=`Ferguson's first FA Cup, achieved after a replay against Crystal Palace, at the time seemed to be a stand-alone success, one that possibly saved his job after another poor season in the League. But nine years later, it seemed that Lee Martin's winning goal against Palace lit the fuse for an explosion of unprecedented success.
    First and foremost, winning the FA Cup in 1990 allowed United to make a return to European competition after an absence of five years following the Heysel disaster. Far from being rusty, the Reds went all the way to the final of the European Cup Winners' Cup in Rotterdam where the opponents were Barcelona, the former club of United striker Mark Hughes. Two goals by Hughes sealed the match 2-1 in United's favour in May 1991, 23 years after the club's previous triumph in Europe. 
    The other long wait, for that elusive League championship, very nearly ended in 1992. The Reds had already won the manager's third trophy in March, the League Cup, and were in a two-horse race with Leeds. Liverpool were out of the running, but still had a say in the destiny of the title, beating United 2-0 at Anfield to end their arch rival's challenge.
    The 1991/92 title would be remembered in Manchester as the title that United lost, rather than the one that Leeds actually won. Leeds, after all, were not the greatest of football powers in the 1990s and their star quality was further reduced when they allowed one of their best players to cross the Pennines in December 1992.
    In selling Eric Cantona to Old Trafford, the Yorkshire club practically handed over the keys to the League championship. The Frenchman brought the little extra bit of magic and confidence that had been missing from United's previous campaigns and was an instant hit with the Mancunian faithful, scoring nine goals to help the Reds win their first title in 26 years.
    In the following season, 1993/94, the team virtually picked itself en route to an historic League and FA Cup Double, with Cantona sporting the number seven shirt that had been Bryan Robson’s property for so long. The number one, meanwhile, was undoubtedly Peter Schmeichel, arguably the best goalkeeper ever seen in the English game.
    Cantona’s eight-month absence from January 1995, following his clash with a fan at Crystal Palace, proved to be United’s undoing as they tried to defend their Double. The Reds surrendered the title by one point to Blackburn Rovers and then lost the FA Cup final by one goal to Everton. The former champions were hampered at Wembley by an injury to Steve Bruce, the brave captain who was a defensive rock in the early 1990s, and his replacement at half-time, Ryan Giggs, was also not fully fit.
    Bruce also missed the following year's FA Cup Final, at the end of the 1995/96 season, but this time the result was rather different. Liverpool stood between United and a first-ever ‘Double Double’ and were holding out for extra-time, when Cantona struck home a sublime shot in the 86th minute. The French skipper had throughout the season been an inspiration to the talented young players in the team, including David Beckham and Gary Neville.
    In May 1997, Cantona helped the club to its fourth League title of the decade. It was to be his last, as he surprisingly retired from football later that same month. The shock waves of Eric’s decision seemed to last for a whole year, as the Reds went empty-handed in 1997/98 while Arsenal won the Double. Again, injuries to key players, especially Giggs and Roy Keane, were cited for United’s downfall.
    The influence that Giggs could have on results was never more apparent than in the 1999 FA Cup semi-final replay, when he scored perhaps the goal of the decade – a solo run and finish that left Arsenal's defenders grasping at thin air. It booked United's place in their fifth FA Cup final of the 1990s, and this time Ferguson's men won it, beating Newcastle United 2-0 with goals by Paul Scholes and substitute Teddy Sheringham.
    That result clinched United's third Double, six days after the Premiership title had been wrapped up by Andy Cole's goal against Tottenham at Old Trafford. But still there was more to come from a remarkable campaign. After an epic Champions League semi-final against Juventus, when Keane inspired the team to fight back from 2-0 down in the second leg, United marched into an epic final against Bayern Munich in Barcelona.
    United's attempts to win the European Cup for the first time since 1968 looked to be doomed when Bayern took an early lead through Mario Basler and defended it with typical German resilience. But then, in injury time, the Reds produced one of the most stunning revivals in sporting history – Sheringham equalised and, moments later, his fellow substitute Ole Gunnar Solskjaer fired in the winner to make the score 2-1. United clinched an unprecedented, historic Treble and Ferguson was subsequently knighted as fans around the globe basked in the glory.
    The Treble became a Quadruple later in the year when Sir Alex's men travelled to Tokyo to compete for the Inter-Continental Cup. Keane's goal against Palmeiras of Brazil bestowed upon United the title of World Club Champions. Officially, at the end of the Millennium, the biggest football club in the world had also become the best in the world!`;


    decade2009=`The January jaunt to South America didn't result in any silverware but it gave the players valuable relaxation time in the sun. Rejuvenated by this, United raced ahead of the rivals in the title race on return to England, after they had failed to capitalise at the start of the year. Sir Alex's men achieved their sixth Premiership title early, in April, and still without a convincing replacement for Peter Schmeichel. 
    A host of goalkeepers, including Mark Bosnich, tried and failed to establish themselves during the 1999/2000 season. So it was hardly surprising when World Cup and European Championship winner Fabien Barthez joined United in July 2000. 
    The eccentric but formidable French goalkeeper helped United to win a third successive title in 2000/01, a feat that had previously been achieved by only a handful of clubs in England. Liverpool had been the last team to do it, in 1982, 1983 and 1984, but this was under the supervision of two different managers - Bob Paisley and Joe Fagan.
    Sir Alex had been at the helm for all three of United's back-to-back titles, and was the first manager in English football to achieve the hat-trick. On the back of this latest trophy, he announced his impending retirement, only to thankfully change his mind and decide to stay.
    Ferguson's major signing in the summer of 2002 was Rio Ferdinand, one of England's best performers at the World Cup finals in Japan and Korea. The £30m acquisition from Leeds added the steel that had arguably been missing from United's defence since the departure of Jaap Stam to Lazio.
    Ferdinand helped the Reds to recapture the Premiership title in May 2003, a season that marked the departure of one of United’s favourite sons. David Beckham left his longtime home by signing for Real Madrid but his career as a Red ended on a high, scoring a trademark free-kick against Everton in his final game.
    Arsenal reclaimed the League title in 2004 but the Reds won the FA Cup for an 11th time, beating Millwall 3-0 in the 2004 final at Cardiff's Millennium Stadium. A year later, United were back in Wales to face Arsenal for the trophy. Chelsea had taken the Premiership and League Cup, and it was the Gunners who triumphed on penalties despite a dominant display from United - for whom Wayne Rooney and Cristiano Ronaldo were outstanding. The following season brought maiden silverware for the pair as the Reds beat Wigan Athletic in the League Cup final.
    For Sir Alex and his players, the main aim remained Premier League glory, which was duly snared the following season as United notched a 16th League title, finishing six points clear of reigning champions Chelsea. While the whole squad performed admirably to snatch the title back from Stamford Bridge, the man who took most of the plaudits was Ronaldo, who collected 13 personal honours during the campaign - including the PFA Player and Young Player of the Year award.
    While it seemed improbable that the winger could top his 2006/07 heroics, he did just that the following season. Ronaldo played a major part - scoring 42 goals - as the Reds saw off the challenge of Chelsea in the two biggest competitions going. Strengthened by the summer signings of Owen Hargreaves, Carlos Tevez, Anderson and Nani, United recovered from a slow start to the season to head the table for almost the entire campaign. Despite a late charge from Chelsea, a final-day victory at Wigan (in which Ryan Giggs scored the clinching goal on the day he equalled the club's all-time appearances record) secured a 17th league title for United.
    Ten days later, in Moscow, the Reds and Blues duked it out for silverware again as two English clubs met in the final of the Champions League or European Cup for the first time. Ronaldo's opener was cancelled out by Frank Lampard and, after 120 tense minutes, the match went to penalties. Ronaldo's miss gave John Terry the chance to take the trophy, but the Chelsea skipper slipped and smacked his effort against a post. Reprieved, United went on to win the shootout when Edwin van der Sar saved Nicolas Anelka's effort, ensuring that Europe's biggest competition had been won by the men from Manchester for a third time.
    How do you top a season like 2007/08? Well, Sir Alex's men did their very best and only defeat at the very last hurdle - against Barcelona in the Champions League final - prevented the Reds from a historic trophy haul. Despite ultimate disappointment in Europe, United dominated almost every other competition. In December, the Reds flew to Japan to compete in the FIFA Club World Cup and a solitary Rooney goal against Ecuador's Liga de Quito in the final was enough to crown United world champions.
    But what sort of effect would a gruelling mid-season trip to the Far East have on the Reds' domestic aspirations? As it turned out, it only made United stronger: Sir Alex's men reeled in Liverpool (seven points clear when the Reds returned from Japan) before going on to win a record-equalling 18th League title. But even before Gary Neville lifted the Barclays Premier League trophy, the Reds had tasted success against Tottenham in the League Cup. On that occasion, goalkeeper Ben Foster was the penalty shootout hero after the scores remained level after 120 minutes. The Reds ended the decade having lifted a remarkable 14 trophies.`;

    decade2019=`There was some solace to be found in the retention of the League Cup, achieved at Aston Villa’s expense and secured by a late winner from Wayne Rooney, whose individual excellence was rewarded with both the PFA Player’s Player of the Year and Football Writers’ Player of the Year awards.
    Despite that single piece of silverware, the 2009/10 campaign was most notable for the heightened stakes of the Manchester derby, with a club takeover inflating the ambition of Manchester City and putting them in the frame for honours. United’s local authority was exerted, however, with home and away Premier League wins and a League Cup semi-final triumph, with each victory dramatically procured in injury-time.
    Both Manchester clubs were intent on bringing the Premier League trophy back to the North-West as the 2010/11 season began, and United’s squad was bolstered by the low-key captures of promising youngsters Javier Hernandez and Chris Smalling.
    Though largely unknown, the duo quickly gelled with the squad and, despite a season of largely unconvincing away form, United reclaimed the title for a record 19th domestic rule. While Rooney had powered the 2009/10 campaign with his prolific form in front of goal, 2010/11 was notably more of a squad success.
    From the goalkeeper Edwin van der Sar – in his last season at the club – through to the ageless influence of Ryan Giggs and Paul Scholes, up to a revitalised Rooney, all hands were at the pump as Chelsea were dethroned.
    A remarkable home record was the cornerstone of the success but, in Europe, it was miserly away form that helped propel the Reds into another Champions League final against Barcelona, this time at Wembley. For the second time in three years, Lionel Messi and co were ultimately too strong for United on the night, but it was that record 19th league title that made it another season to remember at Old Trafford.
    The bid to quickly usher number 20 into the record books looked strong in the early stages of 2011/12. Sir Alex Ferguson strengthened his squad with the signings of David De Gea, Phil Jones and Ashley Young, while homegrown talents Tom Cleverley and Danny Welbeck made the step up to senior regularity.
    Despite a breathtaking start to the campaign, the Reds were rocked by a spate of injuries and a thumping home defeat to City, who had emerged as the only genuine challengers for the title. Having fought on admirably against adversity – and welcomed Scholes back in a shock retirement U-turn, United gradually reeled in Roberto Mancini’s side and, with a month of the season remaining, had built an eight-point lead.
    However, a quickfire run of poor results allowed City to retake the lead on the home straight, and they secured their first title in 44 years in heartbreaking fashion, scoring twice in injury-time on the final day of the season to beat Queens Park Rangers and top the table on goal difference.
    Inevitably, Sir Alex remained defiant, congratulating the new champions while warning: “We’re disappointed about losing the eight-point lead, but I’m not going to have any recriminations for any of my players. They’re a solid bunch of lads and they’ll be fine. Don’t worry about that.”
    Sir Alex's prophecy proved right less than 12 months later when his squad, fired by the aforementioned bitter disappointment and bolstered by the signings of Robin van Persie and Shinji Kagawa, romped to a record 20th league title. The triumph was sealed early on 22 April 2013, with top scorer van Persie appropriately netting a hat-trick in a glorious 3-0 home victory over Aston Villa.
    The end of that 2012/13 season brought the news that millions of Reds had been dreading for a long time: Sir Alex Ferguson was to step down as manager of Manchester United. His retirement was announced on 8 May 2013 and his selection as successor was named the very next day. David Moyes arrived from Everton, tasked with following in the footsteps of British football's most successful manager.
    It proved to be too tall an order for the Scot, despite his impressive if trophy-less track record at Goodison Park. Towards the end of a disappointing 2013/14 season, with United unable to win any of the cup competitions and lying in seventh place, it was announced that Moyes had left the club. On the same day, 22 April 2014, the Reds' longest serving and most-decorated player Ryan Giggs was placed in temporary charge until the end of the season.
    Louis van Gaal's appointmentas the permanent new manager - and the club's first boss from outside the UK and Ireland - was announced on 19 May 2014 and he started work in July after guiding his native Netherlands to the semi-finals of the World Cup in Brazil. Giggs, who had retired in May at the end of a long and glorious one-club playing career, was retained by van Gaal in the role of assistant manager.
    By the close of his first transfer window as United manager, van Gaal had acquired six new players - club record signing Angel Di Maria for £59.7m, Radamel Falcao on loan from Monaco, Daley Blind, Ander Herrera, Marcos Rojo and Luke Shaw - and had allowed many other players to leave, resulting in a much-changed squad for 2014/15.
    With no European fixtures to play, van Gaal's debut season was a purely domestic affair. In the Barclays Premier League, the first objective was achieved as the Reds finished the campaign in the top four and therefore qualified for a return to the Champions League. Further reinforcements for van Gaal's squad came in the summer transfer window of 2015, with the most exciting of the lot arriving in the shape of Anthony Martial, the young French forward from Monaco. But perhaps the most important deal was the new one signed by first-choice keeper David De Gea, who had been pursued by Real Madrid for months prior to his move falling through at the eleventh hour on deadline day.
    Despite a decent start to 2015/16 - United navigated a Champions League qualifying round by beating Bruges home and away and overcoming Liverpool 3-1 at Old Trafford in the league with a debut goal by Martial - it became a difficult campaign with multiple injuries disrupting van Gaal's plans. Luke Shaw's leg fracture was the most serious of these, ruling him out for the rest of the season from September. That blow occurred away to PSV Eindhoven in the Champions League and the Reds later bowed out by finishing third in the group behind the Dutch side and Wolfsburg. A descent into the Europa League led to elimination by Liverpool over two legs in the last-16 round.
    An early exit in the League Cup, at home to Middlesbrough on penalties, was more than compensated for by a stirring run in the FA Cup as van Gaal's men brought the trophy back to Old Trafford for a record-equalling 12th time overall and the first time since 2004. But with United's sometimes patchy league form not good enough to secure a top-four position and a place in the Champions League, media speculation about the manager's future was rife. Forty-eight hours after his team won the cup final at Wembley, van Gaal and the club parted company - his tenure was over, two years into a three-year contract.
    Intense speculation that Jose Mourinho would be appointed as United's new manager proved to be accurate on Friday 27 May 2016 when the club announced his arrival in a statement on ManUtd.com. Executive vice-chairman Ed Woodward commented: "José is quite simply the best manager in the game today... his track record of success is ideal to take the club forward."
    Mourinho himself said: "To become Manchester United manager is a special honour in the game. It is a club known and admired throughout the world. There is a mystique and a romance about it which no other club can match."
    By the time the new 2016/17 Premier League season kicked off, the new boss had already collected his first piece of silverware - the Community Shield, secured with a 2-1 win over league champions Leicester City at Wembley - and he had acquired four exciting new players in Eric Bailly, Zlatan Ibrahmovic, Henrikh Mkhitaryan and club record signing Paul Pogba. The latter embarked on his second spell with United, having previously made seven first-team appearances in 2011/12 after rising through the Academy and Reserves ranks.
    By the end of Mourinho’s debut season at Old Trafford he had added two more trophies, the League Cup sealed with victory over Southampton thanks to Zlatan’s late Wembley winner and, thrillingly, the Europa League, that trophy completing United’s full set of honours after a cup final triumph over Ajax in Stockholm.
    In the summer of 2017, the Reds signed a prolific Premier League striker in Romelu Lukaku from Everton. Mourinho also secured the services of midfielder Nemanja Matic from his former club Chelsea and brought in Sweden centre-back Victor Lindelof from Benfica. Having won the Europa League the previous campaign, United started the 2017/18 season with a UEFA Super Cup clash against Real Madrid, but the Spanish side emerged as 2-1 winners with goals from Isco and Casemiro. The Reds recovered well from the disappointment, winning six of the first seven league games.
    In January 2018, the club signed Alexis Sanchez from Arsenal and the Chilean helped us to amass our best points tally (81) and achieve our highest league position (second, to runaway champions Manchester City) since Sir Alex Ferguson’s departure. We bowed out of the Champions League by losing in the last 16 to Sevilla but we finished the season with the 20th FA Cup final appearance in our history, only for Chelsea to win 1-0 at Wembley and thwart Mourinho's bid for another trophy with United.
    Michael Carrick retired from playing at the end of the 2017/18 season, 12 years after signing for United, and he instantly took up a place on the coaching staff. Meanwhile, three new players were acquired - midfielder Fred, full-back Diogo Dalot and goalkeeper Lee Grant - before the 2018/19 term began with a 2-1 home win against Leicester City. However, the promising start could not be maintained and in December, with the team placed sixth in the Premier League table, the club decided to part company with Mourinho. The Portuguese coach was replaced by former Reds striker Ole Gunnar Solskjaer, who was appointed as caretaker manager until the end of the campaign.`
}